repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.1
  hooks:
  - id: commitizen
    stages:
    - commit-msg

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
    # Run the linter.
    - id: ruff

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.384
  hooks:
  - id: pyright