repos:
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.21.2
  hooks:
  - id: commitizen
    stages:
    - commit-msg

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.2.2
  hooks:
    # Run the linter.
    - id: ruff

- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.366
  hooks:
  - id: pyright